apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "newrelic.com/v1alpha1",
          "kind": "Instrumentation",
          "metadata": {
            "name": "newrelic-instrumentation"
          },
          "spec": {
            "dotnet": {
              "image": "ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-dotnet:latest"
            },
            "go": {
              "image": "ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:latest"
            },
            "java": {
              "image": "ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-java:latest"
            },
            "nodejs": {
              "image": "ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-nodejs:latest"
            },
            "python": {
              "image": "ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-python:latest"
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-12-01T00:18:18Z"
    operators.operatorframework.io/builder: operator-sdk-v1.27.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4-alpha
  name: newrelic-agent-operator.v0.1.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Instrumentation is the Schema for the instrumentations API
      displayName: New Relic Instrumentation
      kind: Instrumentation
      name: instrumentations.newrelic.com
      resources:
      - kind: Pod
        name: ""
        version: v1
      version: v1alpha1
  description: The New Relic agent operator is an admission controller API that enables
    the instrumentation of application workloads (including Java, NodeJS, DotNet,
    and Python) using a custom resource definition.
  displayName: New Relic Agent Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - get
          - list
          - update
        - apiGroups:
          - newrelic.com
          resources:
          - instrumentations
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: newrelic-agent-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/name: newrelic-agent-operator
          control-plane: controller-manager
        name: newrelic-agent-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: newrelic-agent-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                app.kubernetes.io/name: newrelic-agent-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                - --zap-log-level=info
                - --zap-time-encoding=rfc3339nano
                image: ghcr.io/newrelic-experimental/newrelic-agent-operator/newrelic-agent-operator:0.1.2
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  requests:
                    cpu: 100m
                    memory: 64Mi
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              serviceAccountName: newrelic-agent-operator-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: newrelic-agent-operator-controller-manager-service-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: newrelic-agent-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - newrelic
  - instrumentation
  - apm
  links:
  - name: Newrelic Agent Operator
    url: https://newrelic-agent-operator.domain
  maintainers:
  - email: alozoya@newrelic.com
    name: Andrew Lozoya
  maturity: alpha
  provider:
    name: New Relic
    url: newrelic.com
  version: 0.1.2
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: newrelic-agent-operator-controller-manager
    failurePolicy: Fail
    generateName: minstrumentation.kb.io
    rules:
    - apiGroups:
      - newrelic.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - instrumentations
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-newrelic-com-v1alpha1-instrumentation
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: newrelic-agent-operator-controller-manager
    failurePolicy: Ignore
    generateName: mpod.kb.io
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-v1-pod
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: newrelic-agent-operator-controller-manager
    failurePolicy: Fail
    generateName: vinstrumentationcreateupdate.kb.io
    rules:
    - apiGroups:
      - newrelic.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - instrumentations
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-newrelic-com-v1alpha1-instrumentation
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: newrelic-agent-operator-controller-manager
    failurePolicy: Ignore
    generateName: vinstrumentationdelete.kb.io
    rules:
    - apiGroups:
      - newrelic.com
      apiVersions:
      - v1alpha1
      operations:
      - DELETE
      resources:
      - instrumentations
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-newrelic-com-v1alpha1-instrumentation
