---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-java
spec:
  selector:
    matchLabels:
      app: springboot-java
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-java
      annotations:
        instrumentation.newrelic.com/inject-java: "true"
    spec:
      containers:
        - name: springboot-java
          image: ghcr.io/open-telemetry/opentelemetry-operator/e2e-test-app-java:main
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-java-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: springboot-java      
