---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-hello-world
spec:
  selector:
    matchLabels:
      app: express-hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: express-hello-world
      annotations:
        instrumentation.newrelic.com/inject-nodejs: "true"
    spec:
      containers:
        - name: express-hello-world
          image: bschmitt769/express-demo-app:0.1
          ports:
            - containerPort: 3000
          env:
            - name: NODE_PATH
              value: /usr/local/lib/node_modules
---
apiVersion: v1
kind: Service
metadata:
  name: express-hello-world-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: express-hello-world 