---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
spec:
  selector:
    matchLabels:
      app: flask-hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-hello-world
      annotations:
        instrumentation.newrelic.com/inject-python: "true"
    spec:
      containers:
        - name: flask-hello-world
          image: andrewlozoya/flask-hello-world:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask-hello-world 
