---
apiVersion: newrelic.com/v1alpha1
kind: Instrumentation
metadata:
  labels:
    app.kubernetes.io/name: instrumentation
    app.kubernetes.io/created-by: newrelic-agent-operator
  name: newrelic-instrumentation
spec:
  # # A required but separate opentelemetry collector is required for go autoinstrumentation set to 4318.
  # exporter:
  #   endpoint: http://opentelemetry-collector.ao-demo:4318
  # propagators:
  #   - tracecontext
  # sampler:
  #   type: always_on
  # resource:
  #   resourceAttributes:
  #     cluster.name: "your-cluster-name"
  # ### End OTel config ###
  java:
    image: ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-java:8.0.1
    env:
    - name: NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED
      value: "false"
  nodejs:
    image: ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-nodejs:latest
  python:
    image: ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-python:8.8.0
  dotnet:
    image: ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-dotnet-arm:latest
  # php:
  #   image: ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-php:latest
  # go:
  #   image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:latest